"""
Configuration module for file ignore patterns used in code extraction.
"""

from typing import List

# Default patterns to ignore when extracting code
DEFAULT_IGNORE_PATTERNS: List[str] = [
    # Git
    ".git/**",
    ".gitignore",
    ".gitattributes",
    ".gitmodules",
    # Python
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "__pycache__/",
    ".pytest_cache/",
    ".coverage",
    ".tox/",
    ".nox/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".hypothesis/",
    "poetry.lock",
    "Pipfile.lock",
    # Node/JS
    "node_modules/**",
    "bower_components",
    "package-lock.json",
    "yarn.lock",
    ".npm/",
    ".yarn/",
    ".pnpm-store/",
    # Java
    "*.class",
    "*.jar",
    "*.war",
    "*.ear",
    "*.nar",
    "target/",
    ".gradle/",
    "build/",
    ".settings/",
    ".project",
    ".classpath",
    "gradle-app.setting",
    "*.gradle",
    # C/C++
    "*.o",
    "*.obj",
    "*.so",
    "*.dll",
    "*.dylib",
    "*.exe",
    "*.lib",
    "*.out",
    "*.a",
    "*.pdb",
    # Swift/Xcode
    ".build/",
    "*.xcodeproj/",
    "*.xcworkspace/",
    "*.pbxuser",
    "*.mode1v3",
    "*.mode2v3",
    "*.perspectivev3",
    "*.xcuserstate",
    "xcuserdata/",
    ".swiftpm/",
    # Ruby
    "*.gem",
    ".bundle/",
    "vendor/bundle",
    "Gemfile.lock",
    ".ruby-version",
    ".ruby-gemset",
    ".rvmrc",
    # Rust
    "target/",
    "Cargo.lock",
    "**/*.rs.bk",
    # Go
    "bin/",
    "pkg/",
    # .NET
    "bin/",
    "obj/",
    "*.suo",
    "*.user",
    "*.userosscache",
    "*.sln.docstates",
    "packages/",
    "*.nupkg",
    # Version control
    ".svn/",
    ".hg/",
    # Images/media
    "*.svg",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.ico",
    "*.pdf",
    "*.mov",
    "*.mp4",
    "*.mp3",
    "*.wav",
    # Virtual env
    "venv/",
    ".venv/",
    "env/",
    ".env/",
    "virtualenv/",
    # IDEs and editors
    ".idea/",
    ".vscode/",
    ".vs/",
    "*.swp",
    "*.swo",
    "*.swn",
    ".settings/",
    # Misc
    "*.log",
    "*.bak",
    "*.tmp",
    "*.temp",
    ".cache/",
    ".sass-cache/",
    ".eslintcache",
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    "dist/",
    "build/",
    "*.min.js",
    "*.min.css",
    "*.map",
    ".terraform/",
    "*.tfstate*",
    "vendor/",
] 